development:
  adapter: postgresql
  encoding: unicode
  database: joepeloquin_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: joepeloquin_test
  pool: 5
  timeout: 5000